### ISSUE TITLE
Tip - Add a screenshot to your readme... you'll get a lot more traffic

### ISSUE THREAD

**Issue by PySimpleGUI** [flipswitchingmonkey/MosaicMaker#1]
Projects like this one with a nice GUI really benefit from a screenshot being added to the readme.

![image](https://user-images.githubusercontent.com/46163555/75058773-a0129500-54a9-11ea-8752-9e6a0b499ebf.png)

It's easy to add too... just grab the text from when you paste an image into a GitHub issue.  The above image created this text that you can simply paste into your readme.md file.
```
![image](https://user-images.githubusercontent.com/46163555/75058773-a0129500-54a9-11ea-8752-9e6a0b499ebf.png)
```

I like the GUI!

**Comment by PySimpleGUI** [comment]
Oh, and now that I made a few of these, you HAVE to post a picture of what it creates!  It's brilliant stuff!!

**Comment by flipswitchingmonkey** [comment]
Done as well.
