### ISSUE TITLE
pip install ffmpeg-python

### ISSUE THREAD

**Issue by PySimpleGUI** [flipswitchingmonkey/MosaicMaker#2]
It's important to tell people to use that install of ffmpeg.  When I tried `pip install ffmpeg`, it didn't work.  But it then magically and easily worked when I installed `ffmpeg-python`.

I was impressed the preview worked too.  Nicely done.  It's a nice GUI too.

**Comment by flipswitchingmonkey** [comment]
Done 👍   I wasn't expecting anyone to actually run into the repository this soon :)
Thanks for the feedback!
