### ISSUE TITLE
Suggestion - Feedback while the mosaic is being created

### ISSUE THREAD

**Issue by PySimpleGUI** [flipswitchingmonkey/MosaicMaker#3]
Currently the OK button stays depressed while you're making the mosaic. It locks up the GUI briefly.  I'm sure some people close the program thinking it's hung.

If you're able to keep control of the process and do the mosaic in the background, then calling `window.refresh()` on a periodic basis will  stop it from looking like it's hung.

If you're not able to retain control and the operation is a blocking one, then I have used a popup with a message warning the user to be really effective.  

```python
sg.popup_quick_message('Just 1 moment while your\nmosaic is being created',
                       keep_on_top=True, text_color='white', background_color='red', auto_close_duration=1, auto_close=True)
```

creates a little red box that's visible until you call `window.read()` again in your event loop.

![image](https://user-images.githubusercontent.com/46163555/75082482-cc4a0800-54e1-11ea-8648-f0b991169caa.png)

It's not ideal, but at least the user understands what's happening.   It only costs you 1 line of code.

**Comment by flipswitchingmonkey** [comment]
Latest update has progress bars and is running ffmpeg async.

**Comment by PySimpleGUI** [comment]
Oh wow! I LIKE the triple progress bars.  I've never seen anything like that.  I'll be borrowing that design, thank you.

**Comment by PySimpleGUI** [comment]
I also wrote a background thread with an animation for a long running pip upgrade program.

It runs a subprocess as a thread so that the user code continues to run.  Then I simply run a loop that plays a looping GIF animation.  It's good for times were you're running some shell command that doesn't do anything for many seconds.  If I didn't do this, then your GUI is starved and the OS will eventually complain about it, as you've likely learned already since you're running aync now.  Good job on that BTW.  

```python
import subprocess
import PySimpleGUI as sg
import threading

fhandle = open(r'C:\temp\update.txt', 'w')
thread = threading.Thread(target=lambda: subprocess.run('pip list --outdated', shell=True, stdout=fhandle), daemon=True)
thread.start()
while True:
    sg.popup_animated(sg.DEFAULT_BASE64_LOADING_GIF, 'Loading list of packages', time_between_frames=100)
    thread.join(timeout=.1)
    if not thread.is_alive():
        break
sg.popup_animated(None)
fhandle.close()
```

**Comment by PySimpleGUI** [comment]
I just released this demo that is general purpose.  You can run any command and it'll run an animation in parallel so that the program doesn't appear locked up:

```python
import subprocess
import PySimpleGUI as sg
import threading


"""
    Demo - Run a shell command while displaying an animated GIF to inform the user the 
    program is still running.
    If you have a GUI and you start a subprocess to run a shell command, the GUI essentually
    locks up and often the operation system will off to terminate the program for you.

    This demo fixes this situation by running the subprocess as a Thread.   This enables
    the subproces to run async to the main program.  The main program then simply runs a loop,
    waiting for the thread to complete running. 

    The output from the subprocess is saved and displayed in a scrolled popup.
"""


def process_thread():
    global proc
    proc = subprocess.run('pip list', shell=True, stdout=subprocess.PIPE)


thread = threading.Thread(target=process_thread, daemon=True)
thread.start()

while True:
    sg.popup_animated(sg.DEFAULT_BASE64_LOADING_GIF, 'Loading list of packages', time_between_frames=100)
    thread.join(timeout=.1)
    if not thread.is_alive():
        break
sg.popup_animated(None)

output = proc.__str__().replace('\\r\\n', '\n')
sg.popup_scrolled(output)
```
